const DICTIONARY = {

    en: {
        PLAY_AGAIN_QUESTION: "Play again (YES/no)? ",
        CONFIRM: "y",
        MENU_TITLE: "MENU",
        MENU_PLAY_GAME: "1. Play Game",
        MENU_SETTINGS: "2. Settings",
        MENU_EXIT_GAME: "3. Exit Game",
        SETTINGS_TITLE: "SETTINGS",
        SETTINGS_LANGUAGE: "1. Change Language",
        SETTINGS_BACK: "2. Back to Main Menu",
        LANGUAGE_CHOICE: "Choose language (en/no)",
        PLAYER_TURN: "Player {0} it is your turn",
        PLACE_MARK: "Place your mark at: ",
        WINNER: "You win player",
        DRAW: "It's a draw!",
        GAME_OVER: "GAME OVER",
        GAME_MODE_SELECTION: "Select game mode",
        PLAYER_VS_PLAYER: "1. Player vs Player",
        PLAYER_VS_COMPUTER: "2. Player vs Computer",
        COMPUTER_TURN: "Computer's turn",
    },
    no: {
        PLAY_AGAIN_QUESTION: "Spille en gang til (Ja/nei)? ",
        CONFIRM: "j",
        MENU_TITLE: "MENY",
        MENU_PLAY_GAME: "1. Start Spill",
        MENU_SETTINGS: "2. Instillinger",
        MENU_EXIT_GAME: "3. Avslutt Spill",
        SETTINGS_TITLE: "INSTILLINGER",
        SETTINGS_LANGUAGE: "1. Endre Språk",
        SETTINGS_BACK: "2. Tilbake til Hovedmeny",
        LANGUAGE_CHOICE: "Velg Språk (en/no)",
        PLAYER_TURN: "Spiller {0} det er din tur",
        PLACE_MARK: "Plasser merket ditt på: ",
        WINNER: "Spiller {0} vinner!",
        DRAW: "Det ble uavgjort!",
        GAME_OVER: "SPILLET ER OVER",
        GAME_MODE_SELECTION: "Velg spillmodus",
        PLAYER_VS_PLAYER: "1. Spiller mot Spiller",
        PLAYER_VS_COMPUTER: "2. Spiller mot Datamaskin",
        COMPUTER_TURN: "Datamaskinen's tur",
    }
};

export default DICTIONARY;